---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: registry.gitlab.com/ulrichschreiner/go-web-dev
  commands:
    - echo "latest,g$(git rev-parse --short=8 HEAD)" >.tags

- name: publish
  image: plugins/docker
  settings:
    dockerfile: Dockerfile.dev
    repo: quay.io/ulrichschreiner/ansible-shell
    registry: quay.io
    username:
      from_secret: quay_username
    password:
      from_secret: quay_password
