---
# tasks file for Doorman

- name: Get Cluster information
  kubernetes.core.k8s_cluster_info:
  register: api_status

- name: set minor k8s version
  set_fact:
    k8s_minor: "{{ api_status.version.server.kubernetes.minor | int }}"

- name: create keydb
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'keydb.yml.j2') }}"
    wait: yes
  when:
     - not existing_keydb.enabled

- name: create smtp secrets for transports
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'smtp-secret.yml.j2') }}"
  when: item.type == 'email' and not item.spec_from_secret is defined
  loop: "{{ transports }}"

- name: create ldap secrets for users
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'ldap-secret.yml.j2') }}"
  when: item.type == 'ldap' and not item.spec_from_secret is defined
  loop: "{{ users }}"

- name: generate config template
  set_fact:
    config_data: "{{ lookup('template', 'configs.yml.j2') }}"

- name: create doorman config
  kubernetes.core.k8s:
    state: present
    definition: "{{ config_data }}"

- name: create doorman service
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'service.yml.j2') }}"

- name: create doorman ingress
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'ingress.yml.j2') }}"
  when:
    - service.type == "ingress"
    - k8s_minor|int > 18

- name: create doorman ingress (old)
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'ingress-old.yml.j2') }}"
  when:
    - service.type == "ingress"
    - k8s_minor|int < 19

- name: create doorman deployment
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'deployment.yml.j2') }}"