# permissions for end users to edit doormen.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: doorman-editor-role
rules:
- apiGroups:
  - web.controldeck.io
  resources:
  - doormen
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - web.controldeck.io
  resources:
  - doormen/status
  verbs:
  - get
