# permissions for end users to view doormen.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: doorman-viewer-role
rules:
- apiGroups:
  - web.controldeck.io
  resources:
  - doormen
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - web.controldeck.io
  resources:
  - doormen/status
  verbs:
  - get
